mysqli::$report_mode is deprecated
Error: Creation of dynamic property mysqli::$report_mode is deprecated

Fixed by replacing it with the new function.