Massive Bug fix list, previously patched on master but this branch was forked just before so the original code patches had failed to be included for a long time. These fixes make the module far more stable.
Issues Fixed:

Syntax error: Unexpected token H in JSON at position 0 OK HTTP/1.1. 200 OK
FILE: system/library/openbay/ebay.php
###

No products appearing in Manage Items page
###

No orders appearing in Bulk Order Update page
###

Manage Items page not showing eBay marketplace button - not yet tested other marketplaces
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected token operator of value = in extension/openbay/ebay_new.twig at line 388.
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected token operator of value = (end of statement block expected) in extension/openbay/ebay_profile_shipping_national_flat.twig at line 12.
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected token operator of value = (end of statement block expected) in extension/openbay/ebay_profile_shipping_international_flat.twig at line 10.
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected token operator of value = (end of statement block expected) in extension/openbay/ebay_profile_shipping_national_calculated.twig at line 12.
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected token operator of value = (end of statement block expected) in extension/openbay/ebay_profile_shipping_international_calculated.twig at line 10.
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected token punctuation of value . (end of statement block expected) in extension/openbay/ebay_profile_form_generic.twig at line 59.
###

08A ERROR - When listing to eBay, the Dispatch country on the Shipping tab is missing - even after added to the Shipping profile.
08B ERROR - When listing to eBay, the Payments accepted labels on the Payment tab are missing.
08C ERROR - When listing to eBay, the Load profile on the Image tab is not loading.
08D ERROR - When listing to eBay, the Theme list box is empty on the Image tab even though templates exist.
08E ERROR - When listing to eBay, images are not being recognised on the Image tab.
###

OBP version showing as Unknown or missing OpenCart version supplied. (3.0.2.0)
###

OpenBay Pro and Ebay references appears as text_openbay and text_ebay respectively on Manage Items page
###

OpenBay Pro and Ebay references appears as text_openbay and text_ebay respectively on Bulk Order Update page
###

Thumbnail image sizes not saving on profile/ebay
###

Verify button not working/ebay
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected endif tag (expecting closing tag for the for tag defined near line 18) in extension/openbay/ebay_new_bulk.twig at line 19.
###

When using eBay Bulk Upload, the Price field changes from the actual price to NaN. This only happens when the General Settings profile field Price % modification does not have a value, which is the case when creating a General Settings profile before this fix. The default value for Price % modification should be 0 (zero) but before this fix it was defaulting to null. If after this fix is applied the same problem exists, the existing General Settings profiles will need to be resaved (simply clicking Edit and Save on each).
###

When listing a new product to Amazon, the page gives errors on loading.
###

Amazon SKU and Stock not showing of Amazon Stock Updates page
###

Fatal error: Uncaught exception Twig_Error_Syntax with message Unexpected token operator of value = in extension/openbay/amazon_bulk_listing.twig at line 61.
###

ERROR: Fatal error: Uncaught exception Twig_Error_Syntax with message Unknown marketplaces_processing test in extension/openbay/amazon_bulk_linking.twig at line 45.
###

Notice: Undefined index: token in /home/content/10/10124010/html/betplanner/admin/controller/extension/openbay/amazon.php on line 949
###