OC 3.0.3.2 (and up) > Fatal error: Uncaught Exception: Error: Field 'sort_order' doesn't have a default value
Fatal error: Uncaught Exception: Error: Field 'sort_order' doesn't have a default value<br />Error No: 1364<br /> INSERT INTO `oc_event` (`event_id`, `code`, `trigger`, `action`, `status`) VALUES (1, 'activity_customer_add', 'catalog/model/account/customer/addCustomer/after', 'event/activity/addCustomer', 1); 

While this error occur in OC 3.0.3.2, it will also later if the fields have no default value because if no sort_order is submitted (as it will be in most cases).